# Generated by Django 4.0.5 on 2022-08-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Add priority of your Category'),
            preserve_default=False,
        ),
    ]
