# Generated by Django 4.0.5 on 2023-03-08 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('post', '0003_trending_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.subcategory', verbose_name='Select category for the Post'),
        ),
    ]
