# Generated by Django 4.0.5 on 2022-06-10 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Write the Title fo Your Quiz')),
                ('question', models.TextField(verbose_name='Question')),
                ('option_a', models.CharField(max_length=424, verbose_name='Option A')),
                ('option_b', models.CharField(max_length=424, verbose_name='Option B')),
                ('option_c', models.CharField(max_length=424, verbose_name='Option C')),
                ('option_d', models.CharField(blank=True, max_length=424, null=True, verbose_name='Option D')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, verbose_name='Select write answer of the question')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory', verbose_name='Select category for the Question')),
            ],
        ),
    ]
