# Generated by Django 4.0.5 on 2022-08-07 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_trending_priority'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='Select Post ID'),
            preserve_default=False,
        ),
    ]
