# Generated by Django 4.0.5 on 2022-08-07 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('post', '0003_trending_priority'),
        ('quiz', '0002_quiz_title_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_id',
        ),
        migrations.CreateModel(
            name='QuizSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_set', models.TextField(verbose_name='Write the Title of Your Quiz')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory', verbose_name='Select category for the Quiz Set')),
                ('title_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='Select Post Title')),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizset', verbose_name='Select the Title of Your Quiz'),
        ),
    ]
