# Generated by Django 4.0.5 on 2023-03-08 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('post', '0004_alter_post_sub_category'),
        ('quiz', '0004_rename_title_id_quizset_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizset',
            name='post_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.post', verbose_name='Select Post Title'),
        ),
        migrations.AlterField(
            model_name='quizset',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.subcategory', verbose_name='Select category for the Quiz Set'),
        ),
    ]
